"""Added Column PosterPath in FavoriteMovies

Revision ID: 345ecc3039f3
Revises: 604d88a614fb
Create Date: 2024-07-12 20:17:08.031215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '345ecc3039f3'
down_revision = '604d88a614fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_movie', schema=None) as batch_op:
        batch_op.drop_column('poster_path')

    # ### end Alembic commands ###
